name: gh-deploy

on: 
  push:
    branches: 
    - master
    paths:
    - .github/workflows/gh-deploy.yml
    - 'docs/**'
    - package.json
    - yarn.lock

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - run: yarn add -D vuepress
    - run: yarn build
    - run: cp docs/.vuepress/public/CNAME docs/.vuepress/dist/CNAME
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: docs/.vuepress/dist
