name: Gitee Pages Sync

on: page_build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:SDUOJ/OnlineJudge.git
          destination-repo: git@gitee.com:SDUOJ/OnlineJudge.git

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: zhangt2333
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: SDUOJ/OnlineJudge
          branch: gh-pages